workers: 4
batch_size: 192
saved_model: /nfs_shared/STR_Data/graduate_project/SceneTextRecognition/weights/TPS-Resnet-BiLSTM-Attn/best_accuracy.pth
batch_max_length: 25
imgH: 32
imgW: 100
rgb: False
character: /nfs_shared/STR_Data/graduate_project/SceneTextRecognition/weights/TPS-Resnet-BiLSTM-Attn/kr_charset.txt
sensitive: False
PAD: False
Transformation: TPS
FeatureExtraction: ResNet
SequenceModeling: BiLSTM
Prediction: Attn
num_fiducial: 20
input_channel: 1
output_channel: 512
hidden_size: 256